import { Poppins } from "next/font/google";
import "./globals.css";
import SmoothScroll from "@/components/main/SmoothScroll";
import Navbar from "@/components/main/Navbar";
import Footer from "@/components/main/Footer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Astride Furniture",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable}`}>
      <body>
        <Navbar />
        <SmoothScroll />
        {children}
        <Footer />
      </body>
    </html>
  );
}